release = ["-DCMAKE_BUILD_TYPE=Release"]
debug = ["-DCMAKE_BUILD_TYPE=Debug"]
release_no_lp = ["-DCMAKE_BUILD_TYPE=Release", "-DUSE_LP=NO"]
# USE_GLIBCXX_DEBUG is not compatible with USE_LP (see issue983).
glibcxx_debug = ["-DCMAKE_BUILD_TYPE=Debug", "-DUSE_LP=NO", "-DUSE_GLIBCXX_DEBUG=YES"]
minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES"]

ipc_opt_blind = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES", "-DPLUGIN_BLIND_SEARCH_HEURISTIC_ENABLED=YES", "-DPLUGIN_PLUGIN_ASTAR_ENABLED=YES"]
ipc_opt_lmcut = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES", "-DPLUGIN_LANDMARK_CUT_HEURISTIC_ENABLED=YES", "-DPLUGIN_PLUGIN_ASTAR_ENABLED=YES"]
ipc_sat_lama = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES", "-DPLUGIN_LANDMARKS_ENABLED=YES", "-DPLUGIN_FF_HEURISTIC_ENABLED=YES", "-DPLUGIN_ITERATED_SEARCH_ENABLED=YES", "-DPLUGIN_PLUGIN_LAZY_GREEDY_ENABLED=YES", "-DPLUGIN_PLUGIN_LAZY_WASTAR_ENABLED=YES"]
ipc_agl_lama = ipc_sat_lama

DEFAULT = "release"
DEBUG = "debug"
